name: Build LaTeX Docker Image

on:
  workflow_dispatch: # Manual trigger
  push:
    paths:
      - "Dockerfile" # Only run when Dockerfile changes
      - ".github/workflows/build-latex-image.yml" # Trigger on changes to this workflow file

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Git SSL Configuration
        run: |
          echo "Checking Git SSL configuration..."
          git config --global http.sslCAinfo || echo "No CA info set."

      - name: Update CA Certificates
        run: |
          echo "Updating CA certificates..."
          sudo update-ca-certificates

      - name: Set Git CA Certificate File
        run: |
          echo "Setting Git CA certificate file..."
          git config --global http.sslCAinfo /etc/ssl/certs/ca-certificates.crt

      - name: Temporarily Disable SSL Verification (if needed)
        if: failure() # Only runs if previous steps fail
        run: |
          echo "Disabling SSL verification temporarily..."
          git config --global http.sslVerify false

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/latex-build:latest
          build-args: |
            RUN apt-get update
            RUN apt-get install -y --no-install-recommends zip \
                && rm -rf /var/lib/apt/lists/*
